// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR9TniTHTkmbsjvkmDcVbFQM8eVLGmgXg',
    appId: '1:435356226897:web:5a1b216c196d4b5cbdaf70',
    messagingSenderId: '435356226897',
    projectId: 'formatiffinalfirestore',
    authDomain: 'formatiffinalfirestore.firebaseapp.com',
    storageBucket: 'formatiffinalfirestore.appspot.com',
    measurementId: 'G-K5FFT2W9S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOFQlOMtSrWXMpqIHV9iB-Nh8_6dmJSpQ',
    appId: '1:435356226897:android:b94eb04756d85410bdaf70',
    messagingSenderId: '435356226897',
    projectId: 'formatiffinalfirestore',
    storageBucket: 'formatiffinalfirestore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs_gd-zi4bZJAYxmG0fw9kV9tj9MadI04',
    appId: '1:435356226897:ios:6dab0cfc48ce20c0bdaf70',
    messagingSenderId: '435356226897',
    projectId: 'formatiffinalfirestore',
    storageBucket: 'formatiffinalfirestore.appspot.com',
    iosBundleId: 'com.example.exam2firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs_gd-zi4bZJAYxmG0fw9kV9tj9MadI04',
    appId: '1:435356226897:ios:6dab0cfc48ce20c0bdaf70',
    messagingSenderId: '435356226897',
    projectId: 'formatiffinalfirestore',
    storageBucket: 'formatiffinalfirestore.appspot.com',
    iosBundleId: 'com.example.exam2firestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR9TniTHTkmbsjvkmDcVbFQM8eVLGmgXg',
    appId: '1:435356226897:web:3caabcd249715bf3bdaf70',
    messagingSenderId: '435356226897',
    projectId: 'formatiffinalfirestore',
    authDomain: 'formatiffinalfirestore.firebaseapp.com',
    storageBucket: 'formatiffinalfirestore.appspot.com',
    measurementId: 'G-NZLMXBCP7B',
  );
}
